In [78]:
import numpy as np
array_hw=np.array([[5,5,8,8,9,8],[7,7,5,3,5,7],[8,7,8,4,2,6],[9,9,7,3,1,4]])
print(array_hw)

[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]


In [8]:
flat_array=array_hw.flatten()
print(flat_array)
print(np.sort(flat_array))

[5 5 8 8 9 8 7 7 5 3 5 7 8 7 8 4 2 6 9 9 7 3 1 4]
[1 2 3 3 4 4 5 5 5 5 6 7 7 7 7 7 8 8 8 8 8 9 9 9]


In [82]:
array_column = array_hw[array_hw[:, 1].argsort()]
print(array_column)

[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]


In [91]:
array_row = array_hw[:,array_hw[1, :].argsort()]
print(array_row)


[[8 8 9 5 5 8]
 [3 5 5 7 7 7]
 [4 8 2 8 7 6]
 [3 7 1 9 9 4]]


In [66]:
array1[1:,...]

array([[6, 7, 5, 4, 5],
       [9, 7, 6, 4, 3]])

In [33]:
array_hw[...,2:]

array([[8, 8, 9, 8],
       [5, 3, 5, 7],
       [8, 4, 2, 6],
       [7, 3, 1, 4]])

In [32]:
np.square(array_hw)

array([[25, 25, 64, 64, 81, 64],
       [49, 49, 25,  9, 25, 49],
       [64, 49, 64, 16,  4, 36],
       [81, 81, 49,  9,  1, 16]])

In [31]:
array_hw[2,3]

4

In [30]:
array_hw.sum()

145

In [35]:
array_hw.shape

(4, 6)

In [51]:
array_hw.dtype

dtype('int64')

In [39]:
array_hw.nbytes

192